[package]
name = "sudachi_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "sudachi_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"

sudachi = { git = "https://github.com/WorksApplications/sudachi.rs" }
